### ISSUE TITLE
Review HW2

### ISSUE THREAD

**Issue by BUI-studies** [IvanShablii/BUI_Shablii#1]
## task-02 
метод `verifySore`. Використання `Object.assign` є недоцільним. Те шо написано всередині `Object.assign` - норм, просто не треба було це загортати у таку обгортку.

`unmatchedProductsString` - коли докидуєш туди значення, дописуй їх через кому абощо, для того щоб визідна строка виглядала розбірливо для читання.

наприкінці файлу із завданням ти в зміну насправді запишеш строку яку повертає метод `verifyStore`, бо саме він був викликаний останнім. тому краще спочатку створити змінну зі store-ом, а потім виконувати інші операції над ним.

**Comment by IvanShablii** [comment]
обговорили підчас менторської сесії
https://github.com/IvanShablii/BUI_Shablii/tree/main/02-objects
