### ISSUE TITLE
Review lecture_23-05-07

### ISSUE THREAD

**Issue by BUI-studies** [IvanShablii/BUI_Shablii#2]
`рядок 6` - використай метод масиву `map`. він тобі поверне новий масив, а шо в ньому буде ти вирішуватимеш в колбек функції, яку мапу і передаси.

`рядок 14` - кайфую шо використав метод `filter`

все, починаючи з `рядку 19`, читається дуже складно. я дель зрозумів шо там робиться. спробуй використати методи масивів щоб спростити читабельність. там де у тебе HTMLCollection або NodeList перетворюй їх а масив за допомогою `Array.from`

**Comment by IvanShablii** [comment]
Виправив 
https://github.com/IvanShablii/BUI_Shablii/blob/main/lecture_23-05-07/js/script.js
